# frozen_string_literal: true

# Epic AD: AI Agent Detection Layer
# Analyzes posting patterns, content characteristics, and behavioral signals
# to detect and tag potential AI-generated content on the platform.
#
# Detection Signals:
# 1. Posting Velocity    — Too many posts in a short time window
# 2. Content Uniformity  — Repetitive text patterns, similar phrasing
# 3. Timing Regularity   — Machine-like posting intervals (no human variance)
# 4. Engagement Ratio    — High output with zero community interaction
# 5. Linguistic Analysis  — AI-typical markers (perfect grammar, no typos, formulaic)

class AiAgentDetectionService
  # Thresholds
  VELOCITY_THRESHOLD       = 10    # Max posts per hour before flagging
  TIMING_VARIANCE_MIN      = 5.0   # Minimum seconds of variance between posts (humans are irregular)
  ENGAGEMENT_RATIO_MIN     = 0.05  # Min ratio of received replies/favs to posts
  CONTENT_SIMILARITY_MAX   = 0.7   # Max Jaccard similarity between consecutive posts
  AI_KEYWORD_PATTERNS      = [
    /as an ai/i,
    /i cannot provide/i,
    /i'm an artificial/i,
    /language model/i,
    /generated by ai/i,
    /as a large language/i,
  ].freeze

  # Main detection method — returns a hash with detection results
  def self.analyze(status)
    return { ai_detected: false, confidence: 0, signals: [] } unless status.is_a?(Status)

    account = status.account
    signals = []
    confidence = 0.0

    # Signal 1: Posting Velocity
    velocity_score = check_posting_velocity(account)
    if velocity_score > 0
      signals << { type: 'velocity', label: 'Tốc độ đăng bất thường', score: velocity_score }
      confidence += velocity_score * 25
    end

    # Signal 2: Content Pattern (AI keyword markers)
    content_score = check_ai_content_markers(status)
    if content_score > 0
      signals << { type: 'content', label: 'Ngôn ngữ giống AI', score: content_score }
      confidence += content_score * 30
    end

    # Signal 3: Timing Regularity
    timing_score = check_posting_timing(account)
    if timing_score > 0
      signals << { type: 'timing', label: 'Nhịp đăng bài đều như máy', score: timing_score }
      confidence += timing_score * 20
    end

    # Signal 4: Engagement Ratio
    engagement_score = check_engagement_ratio(account)
    if engagement_score > 0
      signals << { type: 'engagement', label: 'Không có tương tác cộng đồng', score: engagement_score }
      confidence += engagement_score * 15
    end

    # Signal 5: Content Similarity (repetitive phrasing)
    similarity_score = check_content_similarity(account, status)
    if similarity_score > 0
      signals << { type: 'similarity', label: 'Nội dung lặp lại bất thường', score: similarity_score }
      confidence += similarity_score * 10
    end

    # Clamp confidence to 0-100
    confidence = [[confidence, 0].max, 100].min.round(1)
    ai_detected = confidence >= 60

    # Persist the result
    update_status_detection(status, ai_detected, confidence) unless status.new_record?

    {
      ai_detected: ai_detected,
      confidence: confidence,
      signals: signals,
    }
  end

  # Batch analysis for recent statuses from an account
  def self.analyze_account(account, limit: 20)
    statuses = account.statuses.order(id: :desc).limit(limit)
    results = statuses.map { |s| { id: s.id, result: analyze(s) } }

    flagged_count = results.count { |r| r[:result][:ai_detected] }
    avg_confidence = results.sum { |r| r[:result][:confidence] } / [results.size, 1].max

    {
      account_id: account.id,
      total_analyzed: results.size,
      flagged_count: flagged_count,
      avg_confidence: avg_confidence.round(1),
      is_likely_bot: flagged_count > (results.size * 0.5),
      results: results,
    }
  end

  private

  # Signal 1: Posts per hour
  def self.check_posting_velocity(account)
    recent_count = account.statuses
                          .where('created_at > ?', 1.hour.ago)
                          .count

    return 0 if recent_count <= VELOCITY_THRESHOLD
    [(recent_count.to_f / VELOCITY_THRESHOLD) - 1.0, 1.0].min
  end

  # Signal 2: AI content markers
  def self.check_ai_content_markers(status)
    text = status.text || ''
    matches = AI_KEYWORD_PATTERNS.count { |pattern| text.match?(pattern) }
    return 0 if matches == 0
    [matches * 0.5, 1.0].min
  end

  # Signal 3: Timing regularity (low variance = machine-like)
  def self.check_posting_timing(account)
    recent = account.statuses
                    .order(id: :desc)
                    .limit(10)
                    .pluck(:created_at)

    return 0 if recent.size < 5

    intervals = recent.each_cons(2).map { |a, b| (a - b).abs }
    mean = intervals.sum / intervals.size
    variance = intervals.map { |i| (i - mean)**2 }.sum / intervals.size
    std_dev = Math.sqrt(variance)

    # Low standard deviation = machine-like regularity
    return 0 if std_dev > TIMING_VARIANCE_MIN
    [1.0 - (std_dev / TIMING_VARIANCE_MIN), 1.0].min
  end

  # Signal 4: Account engagement ratio
  def self.check_engagement_ratio(account)
    total_posts = account.statuses_count
    return 0 if total_posts < 10

    # Check if account has received meaningful engagement
    recent_statuses = account.statuses.order(id: :desc).limit(20)
    total_engagement = recent_statuses.sum { |s| s.favourites_count + s.reblogs_count }
    ratio = total_engagement.to_f / [recent_statuses.size, 1].max

    return 0 if ratio >= ENGAGEMENT_RATIO_MIN
    [1.0 - (ratio / ENGAGEMENT_RATIO_MIN), 1.0].min
  end

  # Signal 5: Content similarity with recent posts (Jaccard-like)
  def self.check_content_similarity(account, current_status)
    recent_texts = account.statuses
                          .where.not(id: current_status.id)
                          .order(id: :desc)
                          .limit(5)
                          .pluck(:text)
                          .compact

    return 0 if recent_texts.empty?

    current_words = Set.new((current_status.text || '').downcase.split(/\W+/))
    return 0 if current_words.empty?

    max_similarity = recent_texts.map do |text|
      other_words = Set.new(text.downcase.split(/\W+/))
      next 0 if other_words.empty?

      intersection = current_words & other_words
      union = current_words | other_words
      intersection.size.to_f / union.size
    end.max

    return 0 if max_similarity < CONTENT_SIMILARITY_MAX
    [(max_similarity - CONTENT_SIMILARITY_MAX) / (1.0 - CONTENT_SIMILARITY_MAX), 1.0].min
  end

  # Persist detection results to the status record
  def self.update_status_detection(status, ai_detected, confidence)
    status.update_columns(
      ai_detected: ai_detected,
      ai_confidence: confidence
    )
  rescue ActiveRecord::StatementInvalid
    # Columns might not exist yet — ignore during migration
  end
end
